<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.ceva.eai.bwce</groupId>
    <artifactId>tibcobase</artifactId>
    <version>[1.0,2.0]</version>    
  </parent>
  <groupId>com.ceva.eai.gr.bwce.partner.emea.panoptes.services</groupId>
  <artifactId>panoptesPartnerService.parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <modules>
    <module>../panoptesPartnerService.module</module>
    <module>../panoptesPartnerService</module>
  </modules>
</project>



 
